import type { Metadata } from 'next';
import { PT_Sans, Bebas_Neue } from 'next/font/google';
import '@/styles/main.scss';

const PTSans = PT_Sans({ subsets: ['latin'], weight: '400' });
const BebasNeue = Bebas_Neue({ subsets: ['latin'], weight: '400' });

export const metadata: Metadata = {
	title: 'Only team',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='en'>
			<body className={BebasNeue.className}>{children}</body>
		</html>
	);
}
